#!/bin/sh
set -e
 if [ "$1" = "upgrade" ] || [ "$1" = "remove" ]; then
  if [ -h /usr/lib/yorick/packages/pkg_setup.i ]; then
      if [ `ls -l /usr/lib/yorick/packages/pkg_setup.i | awk -F" -> " '{ print $2 }'` = "/etc/yorick/packages/pkg_setup.i" ]; then
	  rm -f /usr/lib/yorick/packages/pkg_setup.i
	  rm -f /etc/yorick/packages/pkg_setup_may_use_Y_HOME || true
      fi
  fi

 fi
#DEBHELPER#
