#!/bin/sh
set -e
case $1 in
  purge)
    if [ -e /etc/yorick ]; then
      rm -Rf /etc/yorick
    fi
    if [ -e /usr/lib/yorick ]; then
      rm -Rf /usr/lib/yorick
    fi
    ;;
  remove)
    if [ -x "`which update-yorickdoc 2>/dev/null`" ]; then
	update-yorickdoc --auto
    fi
    ;;
  abort-upgrade)
    [ -e /usr/lib/yorick/packages/pkg_setup.i ] ||
       ln -s /etc/yorick/packages/pkg_setup.i \\
         /usr/lib/yorick/packages/pkg_setup.i
    ;;
esac
#DEBHELPER#
