#!/bin/sh
 if [ "$1" = "configure" ]; then
   if [ -L /usr/doc/yorick ]; then
     rm -f /usr/doc/yorick
   fi
   if [ -r /usr/share/yorick/1.6/yorick-auto.el ]; then
     cp -f /usr/share/yorick/1.6/yorick-auto.el /etc/emacs/site-start.d/50yorick-auto.el
   fi
 fi
