#!/bin/sh
 if [ "$1" = "upgrade" -o "$1" = "remove" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/yorick -a -d /usr/share/doc/yorick ]; then
    ln -sf ../share/doc/yorick /usr/doc/yorick
  fi
  if [ -r /etc/emacs/site-start.d/50yorick-auto.el ]; then
    rm -f /etc/emacs/site-start.d/50yorick-auto.el
  fi
 fi
